# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Your contribution means alot. ğŸ™Œ Join Discord Server (https://discord.gg/HHMs7Eg) for discussing issues, pull-requests, new features, etc.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Make sure you have assigned an issue to this respective PR ğŸ˜‡

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull requestğŸ‰! Thanks alot for your contribution. ğŸ™
